### ISSUE TITLE
草

### ISSUE THREAD

**Issue by Akatsuki1910** [Crow314/NITNC_Assignment#1]
**ｗ　　　　　ｗ**　　　
**ｗ**ｗｗｗｗｗｗｗｗｗｗ
　　**ｗ　　　　　ｗ**　　

　**ｗ**ｗｗｗｗｗｗｗｗ
　**ｗ　　　　　　　ｗ**
　**ｗ**ｗｗｗｗｗｗｗｗ
　**ｗ　　　　　　　ｗ**
　**ｗ**ｗｗｗｗｗｗｗｗ
　　　　　**ｗ**
**ｗ**ｗｗｗｗｗｗｗｗｗｗ
　　　　　**ｗ**
　　　　　**ｗ**
　　　　　**ｗ**

**Comment by Crow314** [comment]
お前の顔が変形するまで殴るぞ(画像略)
